print("Olá! Seja bem-vindo ao nosso processo seletivo! ")
print("Digite seu nome para começarmos! ")
nome = input("Digite seu nome: ")
print(f"Olá {nome}, Tudo bem? ")
print("Agora precisamos que você digite sua idade: ")
idade = int(input("Digite sua idade: "))
print(f"Muito bem! Agora sabemos que você possui {idade} anos de idade!")
print("Digite sua altura para continuarmos o processo! ")
altura = float(input("Digite sua altura: "))
print(f"Você possui altura de {altura} ")
print(f"Parabéns {nome}! ")
print("Agora você está participando do nosso processo seletivo!")
print("Nossa equipe irá analisar as informações, entraremos em contato! ")
print("Agradecemos as informações! ")
print("Até Breve! ")