print("Olá! Seja muito bem-vindo ao bar do Henri! ")
print("Digite seu nome para a comanda! ")
nome = input("Digite seu nome: ")
print(f"Olá {nome}, Tudo bem? ")
print("Agora precisamos que você digite sua idade: ")
idade = int(input("Digite sua idade: "))
if idade >= 18:
    print(f"Muito bem! Agora sabemos que você possui {idade} anos de idade! ")
    print("Escolha uma mesa e sente-se. ")
    print("Qual cerveja o senhor gostaria de pedir? ")
    print(15 * "*")
    print("Antartica ")
    print("Skol ")
    print("Brahma ")
    print("Heineken ")
    print(15 * "*")
    cerveja = input("Escolha a cerveja desejada: ")
    print(f"Certo ja pedi para o garçom trazer a sua {cerveja} geladinha! ")
    resposta1 = input("Gostaria de um acompanhamento?\n ")
    if resposta1.lower() == "sim":
        print(15 * "* ")
        print("Batata frita ")
        print("Bolinho de carne ")
        print("torrada ")
        print(15 * "* ")
        acompanhamento = input("Digite acompanhamento que você deseja: ")
        print(f"Já pedi para a cozinha preparar o(a) {acompanhamento}! ")
        print("Só aguardar um instante!")
    else:
        print("Tudo bem, só aguardar então! ")
else:    
    print("Sinto muito! Você é menor de idade e não atende os requisitos para estar nesse local! ")